steps:
  - name: gcr.io/cloud-builders/docker
    dir: backend
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/mypitch/mypitch-backend:${_TAG}
      - .
images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/mypitch/mypitch-backend:${_TAG}
substitutions:
  _REGION: europe-west4
  _TAG: latest
